class CodeWriter(object):
    def __init__(self):
        ...
    def set_filename(self, filename):
        ...
    def write_artithmetic(self, command):
        ...
    def write_push_pop(self, command):
        ...
